website/techcompass/urls.py
from django.urls import path
from . import views

app_name = "techcompass"

#URLconfig
urlpatterns = [
    path('', views.home_view, name='index'),
    path('roadmap', views.roadmap_view, name='roadmap'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    # path('reset_password', views.reset_password, name='reset_password'),
    path('register', views.register_user, name='register'),
    path('frontend', views.frontend_view, name='frontend'),
    path('dashboard', views.dashboard_view, name='dashboard'),
    path('roadmap/<str:roadmap_name>', views.roadmap_detail_view, name='roadmap_detail'),
    path('course_update', views.course_update_view, name='course_update'),
    path('roadmap_register/<str:roadmap_name>', views.roadmap_register_view, name='roadmap_register'),
    
]

website/website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from techcompass import urls as techcompass_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(techcompass_urls, namespace='techcompass')),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

website/techcompass/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError



def validate_svg(file):
    if not file.name.endswith('.svg'):
        raise ValidationError(u'Error message')

class Roadmap(models.Model):
    title = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    badge = models.FileField(upload_to='badges/',blank=True,null=True,validators=[validate_svg])
    created_at = models.DateTimeField(auto_now_add=True)
    #updated_at = models.DateTimeField(auto_now=True)
    courses_provided = models.ManyToManyField('Course', related_name='roadmaps', blank=True)
    roadmap_link = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title
    
class Course(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    #image = models.ImageField(upload_to='courses/')
    created_at = models.DateTimeField(auto_now_add=True)
    #updated_at = models.DateTimeField(auto_now=True)
    related_to = models.ForeignKey(Roadmap, on_delete=models.CASCADE, related_name='courses')

    videos = models.JSONField(default=list, blank=True)


    def __str__(self):
        return self.title
    
class Progress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='progress')
    roadmap = models.ForeignKey(Roadmap, on_delete=models.CASCADE, related_name='progress')
    completed = models.BooleanField(default=False)
    completed_at = models.DateTimeField(null=True, blank=True)
    completed_courses = models.ManyToManyField(Course, related_name='progress', blank=True)

    def __str__(self):
        return f'{self.user.username} - {self.roadmap.title}'

website/techcompass/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .models import Roadmap, Progress, Course
from django.utils import timezone
from django.core.exceptions import ValidationError
import json




# Create your views here.
def home_view(request):
	# Add your view logic here
	return render(request, 'pages/home.html')

def roadmap_view(request):
	roadmap = Roadmap.objects.all()
	return render(request, 'pages/roadmaps.html', {'roadmaps': roadmap})

@login_required(login_url='/login')
def roadmap_detail_view(request, roadmap_name):
	if request.method == "GET":
		if not Roadmap.objects.filter(title=roadmap_name).exists():
			return HttpResponse(f"Roadmap named: {roadmap_name} not found", status=404)
		roadmap = Roadmap.objects.get(title=roadmap_name)
		courses = roadmap.courses_provided.all()
		completed = Progress.objects.filter(user=request.user, roadmap=roadmap, completed=True)
		roadmaps_list = Roadmap.objects.all()
		p =[]
		inprogress_roadmaps = request.user.progress.filter(completed=False)
		for i in inprogress_roadmaps:
			courses_completed = i.completed_courses.all()
			courses_provided = i.roadmap.courses_provided.all()
			p.append((i,f"{len(courses_completed)/len(courses_provided)*100:.0f}"))
		try:
			progress = Progress.objects.get(user=request.user, roadmap=roadmap)
		except Progress.DoesNotExist:
			return render(request, 'pages/roadmap_detail.html', {'roadmap': roadmap, 'courses': courses,"not_registered":True,'media_url': settings.MEDIA_URL})
		
		completed_courses = progress.completed_courses.all()
		return render(request, 'pages/roadmap_detail.html', {'roadmap': roadmap, 'courses': courses, 'completed_courses': completed_courses,"finished":completed,'in_progress': p,'roadmp_list':roadmaps_list,'media_url': settings.MEDIA_URL})
	else:
		return JsonResponse({'error': 'Invalid request'})
	

@login_required(login_url='/login')
def roadmap_register_view(request, roadmap_name):
	if not Roadmap.objects.filter(title=roadmap_name).exists():
		return HttpResponse(f"Roadmap named: {roadmap_name} not found", status=404)
	roadmap = Roadmap.objects.get(title=roadmap_name)
	try:
		progress = Progress.objects.get(user=request.user, roadmap=roadmap)
	except Progress.DoesNotExist:
		progress = Progress(user=request.user, roadmap=roadmap)
		progress.save()
	return redirect(f'/roadmap/{roadmap_name}')

@login_required(login_url='/login')
def course_update_view(request):
	if request.method == "POST":
		print(request.body)
		body = json.loads(request.body)
		course_title = body['course_title']
		roadmap_id = body['roadmap_id']
		is_checked= body['is_checked']
		print(course_title, roadmap_id, is_checked)
		roadmap = Roadmap.objects.get(id=roadmap_id)
		course = Course.objects.get(title=course_title)
		progress = Progress.objects.get(user=request.user, roadmap=roadmap)
		if is_checked:
			progress.completed_courses.add(course)
			if progress.completed_courses.count() == roadmap.courses_provided.count():
				progress.completed = True
				progress.completed_at = timezone.now()
				progress.save()
			return JsonResponse({'success': 'Course completed'})
		else:
			progress.completed_courses.remove(course)
			progress.completed = False
			progress.completed_at = None
			progress.save()
			return JsonResponse({'success': 'Course not completed'})
	else:
		return JsonResponse({'error': 'Invalid request'})

def login_user(request):
	if request.user.is_authenticated:
		return redirect('/')
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			messages.success(request, ('You have been logged in'))
			return redirect('/dashboard')
		else:
			messages.error(request, ('Invalid username or password'))
			return redirect('/login')
	else:
		return render(request, 'pages/login.html')
	
# def reset_password(request):
# 	return render(request, 'pages/reset_password.html')

def logout_user(request):
	logout(request)
	messages.success(request, ('You have been logged out'))
	return redirect('/')

def register_user(request):
	if request.user.is_authenticated:
		return redirect('/')
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		first_name = request.POST['first_name']
		last_name = request.POST['last_name']
		email = request.POST['email']
		try:
			user = User.objects.create_user(username=username, password=password, first_name=first_name, last_name=last_name, email=email)
			user.save()
		except Exception as e:
			if 'UNIQUE constraint' in str(e):
				messages.error(request, ('Username already exists'))
			#elif 'password does not match' in str(e):
			else:
				messages.error(request, ('Invalid username or password'))
			return render(request, 'pages/register.html')
		login(request, user)
		return redirect('/dashboard')	
	else:
		return render(request, 'pages/register.html')

@login_required(login_url='/login')
def frontend_view(request):

	return render(request, 'pages/frontend.html',{'roadmaps': request.user.roadmaps.all()})


@login_required(login_url='/login')
def dashboard_view(request,success=False):
	completed_roadmaps = request.user.progress.filter(completed=True)
	inprogress_roadmaps = request.user.progress.filter(completed=False)
	roadmaps_list = Roadmap.objects.all()
	p =[]
	for i in inprogress_roadmaps:
		courses_completed = i.completed_courses.all()
		courses_provided = i.roadmap.courses_provided.all()
		p.append((i,f"{len(courses_completed)/len(courses_provided)*100:.0f}"))
	return render(request, 'pages/dashboard.html',{'user': request.user, 'in_progress': p,
	'completed_roadmaps': completed_roadmaps,'roadmp_list':roadmaps_list, 'media_url': settings.MEDIA_URL,"success":success})

website/techcompass/templates/pages/dashboard.html
{% extends 'layouts/base.html' %}
{% block title %}Dashboard{% endblock %}
{% load static %}
{% block cssfiles %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<style>
  .btn:hover{
    opacity: 100%;
    transform:scale(1.04);
    box-shadow: 0px 0px 10px 0px rgba(83,240,251,1);
  }
  
  #badge:hover{
    opacity: 100%;
    transform:scale(1.1);
    box-shadow: 0px 0px 10px 0px rgba(83,240,251,1);
  }
  .scrollable-menu {
    height: auto;
    max-height: 200px;
    overflow-x: hidden;
  }
</style>
{%endblock%}

{% block body %}

<!--NAVBAR-->
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-transparent ">
    <div class="container">
      <!--LOGO-->
      <a class="navbar-brand px-5" href="{% url 'techcompass:index' %}"><img src="{% static 'Icons/Logo.svg' %}" alt="Logo" height="58px" class="logo"></a>
      <!--TOGGLE BTN-->
      <button class="navbar-toggler shadow-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!--SIDEBAR-->
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link mx-4 px-3 fs-4" aria-current="page" href="{% url 'techcompass:index' %}" id="navigation">Home</a>
          </li>
          <li class="nav-item dropdown-center">
            <a class="nav-link dropdown-toggle mx-4 px-3 fs-4" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" id="navigation">
              Explore Roadmaps
            </a>
            <ul class="dropdown-menu dropdown-menu-end text-bg-dark scrollable-menu">
              
              {% for roadmp in roadmp_list %}
                <li><a class="dropdown-item text-white bg-dark" href="{% url 'techcompass:roadmap'%}\{{roadmp.title}}">{{roadmp.title}}</a></li>
                <hr class="dropdown-divider">
              {% endfor %}
                
              
            </ul>
          </li>
          <li class="nav-item">
              <div class="btn-group pt-1">
                <a class="navbar-brand px-5 pt-2 dropdown-center" type="button" data-bs-toggle="dropdown" ><i class="fa-solid fa-user-large"></i></a>
                <ul class="dropdown-menu text-bg-dark">
                  <li><a class="dropdown-item text-white bg-dark" href="#">Dashboard</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item text-white bg-dark" href="{% url 'techcompass:logout' %}">Logout</a></li>
                </ul>
              </div>
          </li>
          
        </ul>
      </div>
    </div>
</nav>

<!--DASHBOARD-->
<div style="height: 40px;"></div>

<div class="container mt-5">
  <!-- Profile Section -->
  <div class="card mb-4 shadow-sm bg-black text-white">
    <div class="card-body text-center">
      <img src="{% static 'Icons/user.jpg' %}" alt="Profile Picture" class="rounded-circle mb-3" style="height:200px; box-shadow: 0px 0px 10px 0px rgba(83,240,251,1);">
      <h3 class="card-title"> Welcome, {{user.first_name}}</h3>
    </div>
  </div>

  <div class="mb-4 text-white">
    <h4>Earned Badges <i class="fa-solid fa-award"></i></h4>
    <div class="row">
      {% for completed in completed_roadmaps %}

      <div class="col-md-4 col-sm-6 mb-3">
        <div class="card text-center shadow-sm bg-black text-white">
          <div class="card-body">
            <a type="button" id="myBadge">
            <img src="{{media_url}}{{completed.roadmap.badge}}" alt="Badge" class="rounded-circle mb-3" style="height:130px" id="badge"></a>
            <h5 class="card-title">{{completed.roadmap.title}}</h5>
          </div>
        </div>
      </div>
      {% endfor %}
      <!-- Repeat Badge Cards -->

    </div>
  </div>

  <!-- Courses in Progress Section -->
  <div class="mb-4 text-white">
    <h4 class="pb-2">Courses in Progress <i class="fa-solid fa-spinner"></i></h4>
    <div class="list-group border border-3 border-info">
      {% for progress in in_progress %}
      <div class="list-group-item text-white bg-black p-3">
        <a href="{% url 'techcompass:roadmap'%}\{{progress.0.roadmap.title}}" style="text-decoration: none;"><h5 class="mb-1 text-white">{{progress.0.roadmap.title}}</h5></a>
        <div class="progress">
          <div class="progress-bar bg-success" role="progressbar" style="width: {{progress.1}}%;" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100">{{progress.1}}%</div>
        </div>
      </div>
      {% endfor %}

      <!-- Repeat for more courses -->
    </div>
  </div>
</div>




  {%endblock%}

website/techcompass/templates/pages/login.html
{% extends 'layouts/base.html' %}
{% block title %}Login{% endblock %}
{% load static %}


{% block cssfiles %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<style>
  body{
    background-color: black;
  }
#floatingInput:focus {
  border-color: rgba(83,240,251,1);
  box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.075) inset, 0px 0px 8px rgba(83,240,251,1);
}
.logo{
   position: relative;
   font-size: 20em;
   text-shadow: 0 0 50px #0f0, 
                  0 0 100px #0f0, 
                  0 0 150px #0f0, 
                  0 0 200px #0f0, 
                  0 0 250px #0f0;
   animation: animate 5s linear infinite;
}

.btn:hover{
    opacity: 100%;
    transform:scale(1.04);
    box-shadow: 0px 0px 10px 0px rgba(83,240,251,1);
  }

#login:hover{
    opacity: 100%;
    transform:scale(1.02);
  }
#login{
    transition: .2s ease-in-out;
  }
  
</style>
{%endblock%}

{% block body %}


<!--{%if messages%}
    {%for message in messages%}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      {{message}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {%endfor%}
    {%endif%}-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-transparent ">
      <div class="container">
        <!--LOGO-->
        <a class="navbar-brand px-5 logo" href="{% url 'techcompass:index' %}"><img src="{% static 'Icons/Logo.svg' %}" alt="Logo" height="58px"></a>
        </div>
      </div>
    </nav>

  <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    
    <div class="container mt-4 px-5 pt-1 border rounded-5 " style="max-width: 80%; box-shadow: 0px 5px 27px 0px rgba(83,240,251,1);" id="login">
      <h2 class="text-center mt-4 mb-5 text-white">Login</h2>
      <form class="text-white" method="post" action="{% url 'techcompass:login' %}">
        {% csrf_token %}
        <div class="row">
          <!-- username -->
          <div class="col-md-6">
            <div class="form-floating mb-3">
              <input type="text" class="form-control bg-transparent text-white" id="floatingInput" name="username" placeholder="Input">
              <label for="floatingInput">Username</label>
            </div>
          </div>
          <!-- create password -->
          <div class="col-md-6">
            <div class="form-floating mb-3">
              <input type="password" class="form-control bg-transparent text-white" id="floatingInput" name="password" placeholder="password">
              <label for="floatingpassword">Password</label>
            </div>
          </div>
        </div>

        
        <div class="d-flex justify-content-center mt-4 mb-4"><button type="submit" class="btn text-black" style="width: 100px; align-content: center; background-color: rgba(83,240,251,1);">Login</button></div>
        <div class="d-flex justify-content-center mt-4 mb-4">New around here?  <a href="{% url 'techcompass:register' %}" class="link-info px-1 text-decoration-none"> Sign Up</a> </div>

      </form>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>


{%endblock %}

website/techcompass/templates/pages/roadmap_detail.html
{% extends "layouts/base.html" %} 
{% load static %} 
{%block title%}
{{roadmap.title}} 
{%endblock%} 
{%block cssfiles%}
<style>
  #credits:hover {
    opacity: 100%;
    transform: scale(1.04);
    color: rgba(83, 240, 251, 1);
  }
  .btn:hover {
    opacity: 100%;
    transform: scale(1.04);
    box-shadow: 0px 0px 10px 0px rgba(83, 240, 251, 1);
  }
  .scrollable-menu {
    height: auto;
    max-height: 200px;
    overflow-x: hidden;
  }
  .test {
    width: 300px;
    padding: 10px;
    margin: 10px;
    border: 1px solid #17a2b8;
    border-radius: 10px;
    box-shadow: 0px 0px 5px 2px rgba(83, 240, 251, 1);
  }
  .container1 {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    width: 100%;
    max-width: 1200px;
  }
 
</style>
{%endblock%} 
{%block body%} 
{% if not_registered %}
<nav class="navbar navbar-expand-lg navbar-dark bg-transparent">
  <div class="container">
    <!--LOGO-->
    <a class="navbar-brand px-5 logo" href="{% url 'techcompass:index' %}"
      ><img src="{% static 'Icons/Logo.svg' %}" alt="Logo" height="58px"
    /></a>
  </div>
</nav>
<div style="height: 100px"></div>
<div class="container pt-5 text-center justify-content-center">
  <img
    src="{{media_url}}{{roadmap.badge}}"
    class="rounded-circle mb-3"
    alt="badge"
    height="200px"
    style="box-shadow: 0px 0px 10px 2px rgba(83, 240, 251, 1)"
  />
  <h1 class="text-center text-white pb-3">{{roadmap.title}}</h1>
  <a
    href="{% url 'techcompass:roadmap_register' roadmap.title %}"
    id="roadmap_register"
    class="btn btn-outline-info mx-4 px-3 fs-5"
    >Start your Journey</a
  >
</div>
<div style="height: 150px"></div>

{% else %}
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-transparent">
  <div class="container">
    <!--LOGO-->
    <a class="navbar-brand px-5" href="{% url 'techcompass:index' %}"
      ><img
        src="{% static 'Icons/Logo.svg' %}"
        alt="Logo"
        height="58px"
        class="logo"
    /></a>
    <!--TOGGLE BTN-->
    <button
      class="navbar-toggler shadow-none border-0"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <!--SIDEBAR-->
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link mx-4 px-3 fs-4"
            aria-current="page"
            href="{% url 'techcompass:index' %}"
            id="navigation"
            >Home</a
          >
        </li>
        <li class="nav-item dropdown-center">
          <a class="nav-link dropdown-toggle mx-4 px-3 fs-4" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" id="navigation">
            Explore Roadmaps
          </a>
          <ul class="dropdown-menu dropdown-menu-end text-bg-dark scrollable-menu">
            
            {% for roadmp in roadmp_list %}
              <li><a class="dropdown-item text-white bg-dark" href="{% url 'techcompass:roadmap'%}\{{roadmp.title}}">{{roadmp.title}}</a></li>
              <hr class="dropdown-divider">
            {% endfor %}
              
            
          </ul>
        </li>
        <li class="nav-item dropdown-center">
          <a
            class="nav-link dropdown-toggle mx-4 px-3 fs-4"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
            id="navigation"
          >
            {{roadmap.title}}
          </a>
          <ul
            class="dropdown-menu dropdown-menu-end text-bg-dark scrollable-menu"
          >
            {% for course in courses %}
            <li>
              <a
                class="dropdown-item text-white bg-dark"
                href="#{{course.title}}"
                >{{course.title}}</a
              >
            </li>
            <hr class="dropdown-divider" />
            {% endfor %}
          </ul>
        </li>
        <li class="nav-item">
          <div class="btn-group pt-2">
            <a
              href="{{roadmap.roadmap_link}}"
              class="btn btn-outline-info mx-2 px-2 fs-5"
              target="blank"
              >Roadmap <i class="fa-solid fa-download"></i
            ></a>
          </div>
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
          <div class="btn-group pt-1">
            <a
              class="navbar-brand px-5 dropdown-center"
              type="button"
              data-bs-toggle="dropdown"
              ><i class="fa-solid fa-user-large"></i
            ></a>
            <ul class="dropdown-menu text-bg-dark">
              <li>
                <a
                  class="dropdown-item text-white bg-dark"
                  href="{% url 'techcompass:dashboard' %}"
                  >Dashboard</a
                >
              </li>
              <li><hr class="dropdown-divider" /></li>
              <li>
                <a
                  class="dropdown-item text-white bg-dark"
                  href="{% url 'techcompass:logout' %}"
                  >Logout</a
                >
              </li>
            </ul>
          </div>
          {% else %}
          <a
            href="{% url 'techcompass:login' %}"
            class="btn btn-outline-info mx-4 px-3 fs-5"
            role="button"
            >Login/Sign Up</a
          >
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>
<div style="height: 100px"></div>
<div class="container">
  {% if roadmap.title == finished.0.roadmap.title %}
  <div class="fs-4 text-white text-center">Your Progress</div>
  <div class="progress">
    <div
      class="progress-bar bg-success"
      role="progressbar"
      style="width: 100%"
      aria-valuenow="70"
      aria-valuemin="0"
      aria-valuemax="100"
    >
      100%
    </div>
  </div>
  <div class="text-white text-center">100% completed</div>
  {% endif %} 
  {% for progress in in_progress %} 
  {% if progress.0.roadmap.title == roadmap.title %}
  <div class="fs-4 text-white text-center">Your Progress</div>
  <div class="progress">
    <div
      class="progress-bar bg-success"
      role="progressbar"
      style="width: {{progress.1}}%;"
      aria-valuenow="70"
      aria-valuemin="0"
      aria-valuemax="100"
    >
      {{progress.1}}%
    </div>
  </div>
  <div class="text-white text-center">{{progress.1}}% completed</div>
  {% elif roadmap.title in completed_courses %} 
  {% endif %} 
  {% endfor %}

  <div class="container text-center">
    <div class="row justify-content-center">
      <b class="text-white p-4" style="font-size: xxx-large"
        >{{roadmap.title}}</b
      >
      <p class="text-white fs-5">{{roadmap.description | safe}}</p>
    </div>
  </div>
  {% for course in courses %}
  <div style="height: 40px"></div>
  <hr class="border border-info border-2" />

  <div id="{{course.title}}" class="pt-5">
    <div class="container-fluid text-center">
      <div class="row justify-content-center">
        <b class="text-white p-4" style="font-size: xxx-large"
          >{{course.title}}</b
        >
        <p class="text-white fs-5">{{course.description | safe}}</p>
        <div class="pt-4">
          <div class="text-center pb-4 text-white">
            <a
              class="btn btn-outline-info px-2"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#collapse{{course.title}}"
              aria-expanded="false"
              aria-controls="collapsehtml"
            >
              Related Youtube Videos &#x25BC;
            </a>
          </div>
        </div>
        <div class="collapse" id="collapse{{course.title}}" style="width: 100%">
          <div class="container1">
            {% for video in course.videos %}

            <div class="test">
                <iframe
                  width="100%"
                  height="auto"
                  src="{{video.1}}"
                  title="YouTube video player"
                  frameborder="0"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                  referrerpolicy="strict-origin-when-cross-origin"
                  allowfullscreen
                ></iframe
                ><br /><a
                  class="text-white pt-3 pb-2"
                  id="credits"
                  href="{{video.2}}"
                  style="text-decoration: none"
                  target="_blank"
                  >Video Credits:
                  <b style="color: rgb(47, 194, 204)">{{video.0}}</b></a
                >
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="form-check text-white">
    {% if course in completed_courses %}
    <input
      class="form-check-input bg-info course_toggle"
      type="checkbox"
      value=""
      id="flexCheckDefault"
      data-from="{{course.title}}"
      checked
    />
    {% else %}
    <input
      class="form-check-input bg-info course_toggle"
      type="checkbox"
      value=""
      id="flexCheckDefault"
      data-from="{{course.title}}"
    />
    {% endif %}
    <label class="form-check-label" for="flexCheckDefault">
      <b>Mark as Complete</b></label
    >
  </div>
  {% endfor %}
</div>

<div style="height: 40px"></div>
{% endif %} 
{%block jsfiles%}
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const course_toggle = document.querySelectorAll(".course_toggle");
    course_toggle.forEach((toggle) => {
      toggle.addEventListener("change", function () {
        const course_title = this.getAttribute("data-from");
        console.log(course_title, "{{roadmap.id}}", "{{csrf_token}}");
        const is_checked = this.checked;
        console.log(course_title, is_checked);
        if (is_checked) {
          fetch(`{% url 'techcompass:course_update' %}`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "X-CSRFToken": "{{csrf_token}}",
            },
            body: JSON.stringify({
              course_title: course_title,
              is_checked: is_checked,
              roadmap_id: "{{roadmap.id}}",
            }),
          })
            .then((response) => response.json())
            .then((data) => {
              console.log(data);
            });
        } else {
          fetch(`{% url 'techcompass:course_update' %}`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "X-CSRFToken": "{{csrf_token}}",
            },
            body: JSON.stringify({
              course_title: course_title,
              is_checked: is_checked,
              roadmap_id: "{{roadmap.id}}",
            }),
          })
            .then((response) => response.json())
            .then((data) => {
              console.log(data);
            });
        }
      });
    });
  });
</script>

{%endblock%} {%endblock%}